name: prueba-crono

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: primer-step
        run: echo "hola mundo"
        
    
